---
- name: Check EC2 Instance Status
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Get EC2 instance information
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ aws_region }}"
        instance_ids: "{{ ec2_instance_ids }}"
      register: ec2data

    - name: Debug EC2 instance states
      ansible.builtin.debug:
        msg: "Instance ID: {{ item.instance_id }} State: {{ item.state.name }}"
      loop: "{{ ec2data.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
    - name: Start stopped instances
      amazon.aws.ec2_instance:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ aws_region }}"
        instance_ids: "{{ ec2_instance_ids }}"
        state: started
      tags: ['never', 'create_ec2start']

    - name: Stop running instances
      amazon.aws.ec2_instance:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ aws_region }}"
        instance_ids: "{{ ec2_instance_ids }}"
        state: stopped
      tags: ['never', 'create_ec2stop']


  vars:
    aws_region: "ap-southeast-2"
    ec2_instance_ids:
      - "i-0516ac157f19996c3"
      - "i-0be2ee1618f655a97"
      # Add more instance IDs as needed
